apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_DSN: "postgres://postgres:12345@{{ .Release.Name }}-postgres-service:5432/library-app?sslmode=disable"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "library-app"
