apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port | int }}
          env:
            - name: DB_DSN
              value: "{{ .Values.app.env.dbDsn }}"
